[package]
name = "nicho_market"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
rand_core = { version = "0.6", features = [ "getrandom" ] }
axum = { version = "0.8.9", features = [ "multipart" ] }
chrono = "0.4.45"
rand = "0.10.2"
serde = { version = "1.0.229", features = [ "derive" ] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = [ "full" ] }
tower_governor = "0.8.0"
uuid = { version = "1.26.0", features = [ "v4" ] }
tower-http = { version = "0.6", features = ["cors"] }
